"""
    BPA

A Julia implementation of the Ball-Pivoting Algorithm for surface reconstruction:

> F. Bernardini, J. Mittleman, H. Rushmeier, C. Silva, G. Taubin,
> "The Ball-Pivoting Algorithm for Surface Reconstruction",
> IEEE Transactions on Visualization and Computer Graphics 5(4), 1999.

The main entry point is [`reconstruct`](@ref), which takes a [`PointCloud`](@ref)
(positions plus oriented normals) and one or more ball radii and returns a
[`BPAMesh`](@ref) interpolating the input points.

# Public API

- `PointCloud(positions, normals)`: input container; accepts vectors of 3-vectors or 3×N /
  N×3 matrices.
- `reconstruct(cloud, rho)`, `reconstruct(cloud, radii)`, `reconstruct(positions, normals, r)`:
  run the algorithm; `verbose = true` prints a line per pass.
- `BPAMesh`: result with `triangles` (vector of `SVector{3,Int}`), the `cloud` they index,
  and `stats::BPAStats`.
- `read_xyz`, `read_ply`, `read_off`, `write_off`, `write_ply`, `write_obj`: file I/O.
- `vertex_normals`, `sample_surface`: turn a triangle mesh into a point cloud with normals
  (for experiments with meshes that have no normals of their own).
- `estimate_spacing`: median nearest-neighbour distance, to choose a radius.
- `estimate_normals`, `orient_normals!`: normals from positions alone (least variance of the
  nearest neighbours) and consistent signs by propagation over a spanning tree (Hoppe et al.
  1992), for clouds whose normals are missing or unsigned. `nearest_neighbors` (not
  exported) is the k-nearest-neighbour search behind them.
- `fill_small_loops`: close small boundary loops of a result by ear clipping. Not part of
  the BPA; the added triangles have no empty ball.
- `check_mesh`: topology of a triangle list (orientable, manifold, boundary loops, components,
  Euler characteristic), for checking a result. `audit_triangles` classifies every triangle
  by the empty-ball property (the correctness test of `compare/`), `boundary_loop_sizes` and
  `component_sizes` give the size distributions, and `report_mesh` prints all of it: the
  report of `bpa.jl --check` and of `tools/check.jl`.
- `fibonacci_sphere`, `torus`, `plane_patch` (not exported): synthetic point clouds with
  analytic normals, for tests and the comparison harness in `compare/`.
- `main(args)`: the command-line tool behind `bpa.jl` (`julia bpa.jl -h`). Its helpers
  `read_xf` and `transform` (not exported) apply the 4×4 `.xf` matrices of registered
  range scans to a point cloud. `check_main` and `sweep_main` (not exported) are the
  entry points of `tools/check.jl` and `tools/sweep.jl`, and `write_stats` the JSON run
  record of `--stats`.

# Source layout

| file | contents | paper section |
| --- | --- | --- |
| `types.jl` | `PointCloud`, `FrontEdge`, `Front`, `BPAMesh`, `BPAStats` | 4 |
| `grid.jl` | voxel grid and the two spatial queries | 4.1 |
| `geometry.jl` | ball centres, pivot trajectory and first-contact angle | 4.2, 4.3 |
| `front.jl` | front bookkeeping, `join!`, `glue!`, manifold tests | 4.4 |
| `seed.jl` | seed triangle search | 4.2 |
| `pivot.jl` | `ball_pivot` | 4.3 |
| `reconstruct.jl` | the main loop (Fig. 5) and multiple passes | 4, 4.6 |
| `io.jl` | XYZ / PLY / OFF input, OBJ / PLY output, mesh sampling | — |
| `spacing.jl` | sample spacing estimate | — |
| `normals.jl` | normal estimation and orientation (Hoppe et al. 1992) | — |
| `fill.jl` | `fill_small_loops`: hole filling by ear clipping, after the reconstruction | — |
| `check.jl` | `check_mesh`, `audit_triangles`, `report_mesh`: topology and empty-ball audit of a triangle list | — |
| `synthetic.jl` | synthetic point clouds with analytic normals | — |
| `cli.jl` | command-line interface | — |
| `tools.jl` | entry points of `tools/check.jl` and `tools/sweep.jl`, the JSON run record | — |

`docs/algorithm.md` walks through the algorithm, the conventions and the invariants;
`docs/LITERATE.md` is the core source read in the paper's order, generated by `docs/literate.jl`.
"""
module BPA

using LinearAlgebra
using StaticArrays
using Random

export PointCloud, BPAMesh, BPAStats, reconstruct, estimate_spacing
export read_xyz, read_ply, read_off, write_ply, write_obj, write_off, vertex_normals, sample_surface
export MeshCheck, check_mesh, BallAudit, audit_triangles, boundary_loop_sizes, component_sizes, report_mesh
export estimate_normals, orient_normals!, fill_small_loops

include("types.jl")
include("grid.jl")
include("geometry.jl")
include("front.jl")
include("seed.jl")
include("pivot.jl")
include("reconstruct.jl")
include("io.jl")
include("spacing.jl")
include("normals.jl")
include("fill.jl")
include("check.jl")
include("synthetic.jl")
include("cli.jl")
include("tools.jl")

end # module
